# -*- coding: utf-8 -*-
"""food_images_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLKyVRKKHDaDULxK5cLnAcl3p_gKn_W4?usp=sharing
"""

import copy
import os
import random
import shutil
import tarfile
from copy import deepcopy
from urllib.request import urlretrieve

import albumentations as A
import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from albumentations.pytorch import ToTensorV2
from torch.utils.data import DataLoader, Dataset, random_split
from torchvision import datasets, models, transforms
from tqdm import tqdm

pd.set_option("display.max_colwidth", None)
random.seed(42)

import gc
torch.cuda.empty_cache()
gc.collect()

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

def display_image_grid(images_filepaths, predicted_labels=(), predicted_probs=(), cols=5):
    rows = len(images_filepaths) // cols
    figure, ax = plt.subplots(nrows=rows, ncols=cols, figsize=(12, 6))
    for i, image_filepath in enumerate(images_filepaths):
        image = cv2.imread(image_filepath)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        true_label = os.path.normpath(image_filepath).split(os.sep)[-2]
        predicted_label = predicted_labels[i] if predicted_labels else true_label
        predicted_prob = predicted_probs[i] if predicted_probs else 1
        color = "green" if true_label == predicted_label else "red"
        if color=='red':
            print(f'true_label: {true_label}, predicted_label: {predicted_label}')
        ax.ravel()[i].imshow(image)
        ax.ravel()[i].set_title(f'{predicted_label}, p={predicted_prob:.2f}', color=color)
        ax.ravel()[i].set_axis_off()
    plt.tight_layout()
    plt.show()

class TqdmUpTo(tqdm):
    def update_to(self, b=1, bsize=1, tsize=None):
        if tsize is not None:
            self.total = tsize
        self.update(b * bsize - self.n)


def download_url(url, filepath):
    directory = os.path.dirname(os.path.abspath(filepath))
    os.makedirs(directory, exist_ok=True)
    print(filepath, os.path.exists(filepath))
    if os.path.exists(filepath):
        print("Filepath already exists. Skipping download.")
        return False

    with TqdmUpTo(
        unit="B",
        unit_scale=True,
        unit_divisor=1024,
        miniters=1,
        desc=os.path.basename(filepath),
    ) as t:
        urlretrieve(url, filename=filepath, reporthook=t.update_to, data=None)
        t.total = t.n
    return True


def extract_archive(filepath):
    extract_dir = os.path.dirname(os.path.abspath(filepath))
    shutil.unpack_archive(filepath, extract_dir)

url = "http://data.vision.ee.ethz.ch/cvl/food-101.tar.gz"

# dataset_directory = os.path.join(os.environ["HOME"], "datasets/food101")
if os.name == "nt":  # Windows
    dataset_directory = "datasets/food101/"
else:  # POSIX (Linux, macOS, etc.)
    home_path = os.environ.get("HOME")
    dataset_directory = os.path.join(home_path, "datasets/food101")

filepath = os.path.join(dataset_directory, "food101.tar.gz")
need_to_extract = download_url(
    url=url,
    filepath=filepath,
)
if need_to_extract:
    extract_archive(filepath)

"""### Dataloaders

"""

all_images_filepaths = []
images_all_path = os.path.join(dataset_directory, "food-101/images")
class_names = os.listdir(images_all_path)
for class_name in class_names:
    all_images_filepaths.extend(
        [
            *sorted(
                [
                    os.path.join(os.path.join(images_all_path, f"{class_name}"), f)
                    for f in os.listdir(os.path.join(images_all_path, f"{class_name}"))
                ]
            )
        ]
    )

def visualize_augmentations_A(dataset, idx=0, samples=10, cols=5):
    dataset = copy.deepcopy(dataset)
    dataset.transform = A.Compose([t for t in dataset.transform if not isinstance(t, (A.Normalize, ToTensorV2))])
    rows = samples // cols
    figure, ax = plt.subplots(nrows=rows, ncols=cols, figsize=(12, 6))
    for i in range(samples):
        image, _ = dataset[idx]
        ax.ravel()[i].imshow(image)
        ax.ravel()[i].set_axis_off()
    plt.tight_layout()
    plt.show()

class OwnDataset(Dataset):
    def __init__(self, class_names, images_filepaths, transform=None):
        self.images_filepaths = images_filepaths
        self.transform = transform
        self.labels_dict = {class_name:i for i, class_name in enumerate(class_names)}

    def __len__(self):
        return len(self.images_filepaths)

    def __getitem__(self, idx):
        image_filepath = self.images_filepaths[idx]
        image = cv2.imread(image_filepath)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        label = self.labels_dict[os.path.normpath(image_filepath).split(os.sep)[-2]]
        if self.transform is not None:
            image = self.transform(image=image)["image"]
        return image, label#torch.tensor([label])

NUM_WORKERS = os.cpu_count()


def split_data(dataset, val_size=0.2, seed=42):
    """ """
    generator = torch.Generator().manual_seed(seed)
    train_data, test_data = random_split(
        dataset, [1 - val_size, val_size], generator=generator
    )

    return train_data, test_data


def create_dataloaders(
    data_dir: str,
    train_transform: transforms.Compose,
    test_transform: transforms.Compose,
    batch_size: int,
    num_workers: int = NUM_WORKERS,
):
    """Creates training and testing DataLoaders.

    Takes in a training directory and testing directory path and turns
    them into PyTorch Datasets and then into PyTorch DataLoaders.

    Args:
        data_dir: Path to image directory.
        train_transform: torchvision transforms to perform on training data.
        test_transform: torchvision transforms to perform on valid and testing data.
        batch_size: Number of samples per batch in each of the DataLoaders.
        num_workers: An integer for number of workers per DataLoader.

    Returns:
        A tuple of (train_dataloader, valid_dataloader, test_dataloader, class_names).
        Where class_names is a list of the target classes.
        Example usage:
        train_dataloader, valid_dataloader, test_dataloader, class_names = \
            = create_dataloaders(data_dir=path/to/train_dir,
                                train_transform=some_transform,
                                test_transform=some_transform,
                                batch_size=32,
                                num_workers=4)
    """

    all_images_filepaths = []
    class_names = os.listdir(data_dir)
    for class_name in class_names:
        all_images_filepaths.extend(
            [
                *sorted(
                    [
                        os.path.join(os.path.join(data_dir, f"{class_name}"), f)
                        for f in os.listdir(os.path.join(data_dir, f"{class_name}"))
                    ]
                )
            ]
        )

    # Get class names
    class_names = os.listdir(data_dir)
    random.shuffle(all_images_filepaths)
    # all_images_filepaths = all_images_filepaths[:250]
    # all_images_filepaths = [i for i in deepcopy(all_images_filepaths) if cv2.imread(i) is not None]
    train_images_filepaths = all_images_filepaths[:int(0.8 * len(all_images_filepaths))]
    val_images_filepaths = all_images_filepaths[int(0.8 * len(all_images_filepaths)):-20]
    test_images_filepaths = all_images_filepaths[-20:]

    train_set = OwnDataset(class_names=class_names, images_filepaths=train_images_filepaths, transform=train_transform)
    valid_set = OwnDataset(class_names=class_names, images_filepaths=val_images_filepaths, transform=test_transform)
    test_set = OwnDataset(class_names=class_names, images_filepaths=test_images_filepaths, transform=test_transform)

    visualize_augmentations_A(train_set)


    # Turn images into data loaders
    train_dataloader = DataLoader(
        train_set,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
    )
    vaild_dataloader = DataLoader(
        valid_set,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
    )

    test_dataloader = DataLoader(
        test_set,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
    )

    return train_dataloader, vaild_dataloader, test_dataloader, class_names, train_images_filepaths, val_images_filepaths, test_images_filepaths

# try:
#     from torchinfo import summary
# except:
#     print("[INFO] Couldn't find torchinfo... installing it.")
#     #!pip install -q torchinfo
#     from torchinfo import summary

from torchinfo import summary
from pathlib import Path

data_path = Path(dataset_directory)
image_path = data_path / "food-101" / "images"

# Create a transforms pipeline manually (required for torchvision < 0.13)
train_transform = A.Compose(
    [
        A.Resize(224, 224),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.5),
        A.Affine(scale=(0.9, 1.1), translate_percent=(0.0, 0.2), rotate=(-45, 45), shear=(-15, 15), mode=cv2.BORDER_REFLECT_101, p=0.5),
        A.CoarseDropout(p=0.55),
        A.Normalize(
            mean=(
                0.485,
                0.456,
                0.406,
            ),  # 3. A mean of [0.485, 0.456, 0.406] (across each colour channel)
            std=(0.229, 0.224, 0.225),
        ),  # 4. A standard deviation of [0.229, 0.224, 0.225] (across each colour channel),
        ToTensorV2(),
    ]
)

test_transform = A.Compose(
    [
        A.Resize(224, 224),
        A.Normalize(
            mean=(
                0.485,
                0.456,
                0.406,
            ),  # 3. A mean of [0.485, 0.456, 0.406] (across each colour channel)
            std=(0.229, 0.224, 0.225),
        ),  # 4. A standard deviation of [0.229, 0.224, 0.225] (across each colour channel),
        ToTensorV2(),
    ]
)

import torch
from tqdm.auto import tqdm
from typing import Dict, List, Tuple


def train_step(
    model: torch.nn.Module,
    dataloader: torch.utils.data.DataLoader,
    loss_fn: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler: torch.optim.lr_scheduler,
    device: torch.device,
) -> Tuple[float, float]:
    """Trains a PyTorch model for a single epoch.

    Turns a target PyTorch model to training mode and then
    runs through all of the required training steps (forward
    pass, loss calculation, optimizer step).

    Args:
    model: A PyTorch model to be trained.
    dataloader: A DataLoader instance for the model to be trained on.
    loss_fn: A PyTorch loss function to minimize.
    optimizer: A PyTorch optimizer to help minimize the loss function.
    scheduler: A PyTorch scheduler.
    device: A target device to compute on (e.g. "cuda" or "cpu").

    Returns:
    A tuple of training loss and training accuracy metrics.
    In the form (train_loss, train_accuracy). For example:

    (0.1112, 0.8743)
    """
    # Put model in train mode
    model.train()

    # Setup train loss and train accuracy values
    train_loss, train_acc = 0, 0
    # Loop through data loader data batches
    for batch, (X, y) in tqdm(enumerate(dataloader)):
        # Send data to target device
        X, y = X.to(device), y.to(device)

        # 1. Forward pass
        y_pred = model(X)

        # 2. Calculate  and accumulate loss
        loss = loss_fn(y_pred, y)
        train_loss += loss.item()

        # 3. Optimizer zero grad
        optimizer.zero_grad()

        # 4. Loss backward
        loss.backward()

        # 5. Optimizer step
        optimizer.step()

        # Calculate and accumulate accuracy metric across all batches
        y_pred_class = torch.argmax(torch.softmax(y_pred, dim=1), dim=1)
        train_acc += (y_pred_class == y).sum().item() / len(y_pred)
    scheduler.step()
    # Adjust metrics to get average loss and accuracy per batch
    train_loss = train_loss / len(dataloader)
    train_acc = train_acc / len(dataloader)
    return train_loss, train_acc


def test_step(
    model: torch.nn.Module,
    dataloader: torch.utils.data.DataLoader,
    loss_fn: torch.nn.Module,
    device: torch.device,
) -> Tuple[float, float]:
    """Tests a PyTorch model for a single epoch.

    Turns a target PyTorch model to "eval" mode and then performs
    a forward pass on a testing dataset.

    Args:
    model: A PyTorch model to be tested.
    dataloader: A DataLoader instance for the model to be tested on.
    loss_fn: A PyTorch loss function to calculate loss on the test data.
    device: A target device to compute on (e.g. "cuda" or "cpu").

    Returns:
    A tuple of testing loss and testing accuracy metrics.
    In the form (test_loss, test_accuracy). For example:

    (0.0223, 0.8985)
    """
    # Put model in eval mode
    model.eval()

    test_loss, test_acc = 0, 0
    with torch.inference_mode():
        # Loop through DataLoader batches
        for batch, (X, y) in enumerate(dataloader):
            # Send data to target device
            X, y = X.to(device), y.to(device)

            # 1. Forward pass
            test_pred_logits = model(X)

            # 2. Calculate and accumulate loss
            loss = loss_fn(test_pred_logits, y)
            test_loss += loss.item()

            # Calculate and accumulate accuracy
            test_pred_labels = test_pred_logits.argmax(dim=1)
            test_acc += (test_pred_labels == y).sum().item() / len(test_pred_labels)

    # Adjust metrics to get average loss and accuracy per batch
    test_loss = test_loss / len(dataloader)
    test_acc = test_acc / len(dataloader)
    return test_loss, test_acc


def train(
    model: torch.nn.Module,
    train_dataloader: torch.utils.data.DataLoader,
    valid_dataloader: torch.utils.data.DataLoader,
    optimizer: torch.optim.Optimizer,
    scheduler: torch.optim.lr_scheduler,
    loss_fn: torch.nn.Module,
    epochs: int,
    device: torch.device,
) -> Dict[str, List]:
    """Trains and tests a PyTorch model.

    Passes a target PyTorch models through train_step() and test_step()
    functions for a number of epochs, training and testing the model
    in the same epoch loop.

    Calculates, prints and stores evaluation metrics throughout.

    Args:
    model: A PyTorch model to be trained and tested.
    train_dataloader: A DataLoader instance for the model to be trained on.
    valid_dataloader: A DataLoader instance for the model to be tested on.
    optimizer: A PyTorch optimizer to help minimize the loss function.
    loss_fn: A PyTorch loss function to calculate loss on both datasets.
    epochs: An integer indicating how many epochs to train for.
    device: A target device to compute on (e.g. "cuda" or "cpu").

    Returns:
    A dictionary of training and testing loss as well as training and
    testing accuracy metrics. Each metric has a value in a list for
    each epoch.
    In the form: {train_loss: [...],
              train_acc: [...],
              test_loss: [...],
              test_acc: [...]}
    For example if training for epochs=2:
             {train_loss: [2.0616, 1.0537],
              train_acc: [0.3945, 0.3945],
              test_loss: [1.2641, 1.5706],
              test_acc: [0.3400, 0.2973]}
    """
    # Create empty results dictionary
    results = {"train_loss": [], "train_acc": [], "test_loss": [], "test_acc": []}

    # Make sure model on target device
    model.to(device)
    # Loop through training and testing steps for a number of epochs
    for epoch in tqdm(range(epochs)):
        train_loss, train_acc = train_step(
            model=model,
            dataloader=train_dataloader,
            loss_fn=loss_fn,
            optimizer=optimizer,
            scheduler=scheduler,
            device=device,
        )
        test_loss, test_acc = test_step(
            model=model, dataloader=valid_dataloader, loss_fn=loss_fn, device=device
        )
        # print(scheduler.get_last_lr(), type(scheduler.get_last_lr()))
        # Print out what's happening
        print(
            f"Epoch: {epoch+1} | "
            f"train_loss: {train_loss:.4f} | "
            f"train_acc: {train_acc:.4f} | "
            f"test_loss: {test_loss:.4f} | "
            f"test_acc: {test_acc:.4f} | "
            f"lr: {scheduler.get_last_lr()[0]:.4f} "
        )

        # Update results dictionary
        results["train_loss"].append(train_loss)
        results["train_acc"].append(train_acc)
        results["test_loss"].append(test_loss)
        results["test_acc"].append(test_acc)

        torch.save(
            {
                "epoch": epochs,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "loss": loss_fn,
                "results" : results
            },
            f"{epochs}_iter.pth",
        )
        print(train_loss, train_acc)

    # Return the filled results at the end of the epochs
    return results

"""## MobileNet"""

weights = (
    torchvision.models.MobileNet_V3_Large_Weights.DEFAULT)  # .DEFAULT = best available weights from pretraining on ImageNet
auto_transforms = weights.transforms()
model = torchvision.models.mobilenet_v3_large(
    weights="MobileNet_V3_Large_Weights.IMAGENET1K_V2")

auto_transforms

auto_transforms

model.classifier

# for param in model.features.parameters():
#     param.requires_grad = False

torch.manual_seed(42)
torch.cuda.manual_seed(42)

output_shape = len(class_names)
model.classifier = torch.nn.Sequential(
    torch.nn.Linear(
        in_features=960,
        out_features=1280,  # same number of output units as our number of classes
        bias=True,
    ),
    torch.nn.Hardswish(),
    torch.nn.Dropout(p=0.2, inplace=True),
    torch.nn.Linear(
        in_features=1280,
        out_features=output_shape,  # same number of output units as our number of classes
        bias=True,
    ),
)#.to(device)

summary(
    model,
    input_size=(
        32,
        3,
        224,
        224,
    ),  # make sure this is "input_size", not "input_shape" (batch_size, color_channels, height, width)
    verbose=0,
    col_names=["input_size", "output_size", "num_params", "trainable"],
    col_width=20,
    row_settings=["var_names"],
)


"""# Train (1 point)"""

loss_fn = nn.CrossEntropyLoss()
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001) # дефолт
optimizer = optim.Adam(model.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.MultiplicativeLR(optimizer, lr_lambda=lambda epoch: 0.92)
n_epochs = 30

NUM_WORKERS

batch_size = 100

train_dataloader, valid_dataloader, test_dataloader, class_names, train_images_filepaths, val_images_filepaths, test_images_filepaths = create_dataloaders(
    data_dir=image_path,
    train_transform=train_transform,
    test_transform=test_transform,
    batch_size=batch_size,
    num_workers=2,
)

# train_dataloader, valid_dataloader,test_dataloader, class_names

len(train_dataloader.dataset)

# print(image_path)

torch.manual_seed(42)
torch.cuda.manual_seed(42)

# Start the timer
from timeit import default_timer as timer

start_time = timer()

# Setup training and save the results
results = train(
    model=model,
    train_dataloader=train_dataloader,
    valid_dataloader=valid_dataloader,
    optimizer=optimizer,
    scheduler=scheduler,
    loss_fn=loss_fn,
    epochs=n_epochs,
    device=device,
)

# End the timer and print out how long it took
end_time = timer()
print(f"[INFO] Total training time: {end_time-start_time:.3f} seconds")

# model.eval()
# model.load_state_dict(torch.load("30_iter.pth")["model_state_dict"])

def plot_loss_curves(results):
    """Plots training curves of a results dictionary.

    Args:
        results (dict): dictionary containing list of values, e.g.
            {"train_loss": [...],
             "train_acc": [...],
             "test_loss": [...],
             "test_acc": [...]}
    """
    loss = results["train_loss"]
    test_loss = results["test_loss"]

    accuracy = results["train_acc"]
    test_accuracy = results["test_acc"]

    epochs = range(len(results["train_loss"]))

    plt.figure(figsize=(15, 7))

    # Plot loss
    plt.subplot(1, 2, 1)
    plt.plot(epochs, loss, label="train_loss")
    plt.plot(epochs, test_loss, label="test_loss")
    plt.title("Loss")
    plt.xlabel("Epochs")
    plt.legend()

    # Plot accuracy
    plt.subplot(1, 2, 2)
    plt.plot(epochs, accuracy, label="train_accuracy")
    plt.plot(epochs, test_accuracy, label="test_accuracy")
    plt.title("Accuracy")
    plt.xlabel("Epochs")
    plt.legend()

plot_loss_curves(torch.load(f"{n_epochs}_iter.pth")['results'])

test_loss, test_acc = test_step(
    model= model,
    dataloader= test_dataloader,
    loss_fn= loss_fn,
    device= device,
)

model = model.eval()
predicted_labels = []
predicted_probs = []
labels_dict_inverted = {i:class_name for i, class_name in enumerate(class_names)}
with torch.no_grad():
    for images, y in test_dataloader:
        # print(images)
        images = images.to(device, non_blocking=True)
        output = model(images)
        predictions_list = list(output.argmax(dim=1).cpu().numpy())
        predictions_prob_list = list(torch.max(torch.softmax(output, dim=1), dim=1))
        predicted_labels.extend(list(map(lambda x: labels_dict_inverted[x], predictions_list)))
        predicted_probs.extend(predictions_prob_list[0].cpu().numpy())
display_image_grid(test_images_filepaths, predicted_labels, predicted_probs)
